### ISSUE TITLE
Empty Array versus Scalar Array Shape Convention

### ISSUE THREAD

**Issue by djl11** [data-apis/consortium-feedback#11]
I was unable to determine the difference between shapes () and (0,) for arrays in the standard. For example nothing is mentioned for the method [reshape](https://data-apis.org/array-api/latest/API_specification/generated/signatures.manipulation_functions.reshape.html?highlight=reshape), the attribute [shape](https://data-apis.org/array-api/latest/API_specification/generated/signatures.array_object.array.shape.html?highlight=shape#signatures.array_object.array.shape), or the [array object](https://data-apis.org/array-api/latest/API_specification/array_object.html) references.

My confusion comes when running the [test_full](https://github.com/data-apis/array-api-tests/blob/master/array_api_tests/test_creation_functions.py#L361) unit test, although I'm sure the same is true for other tests. Essentially both () and (0,) shapes are expected to return a non-empty array in the line ph.assert_fill.

Does the standard support empty arrays? If so, where can I find a description of the shape convention for empty arrays versus scalar shapeless arrays. Any help appreciated!

**Comment by honno** [comment]
The standard definitely has been expected to support 0-sized arrays, although I can see if there's confusion in that regard.

Generally there is the expectation to support 0-_sided_ arrays. To clarify my terminology, I use "side" to mean the size of a single axis, e.g. 0-sided arrays could have shapes like `(0,)`, `(1, 0, 1)`, etc..

And yep, `()`-shaped arrays are _not_ empty, ala "array scalars" in NumPy. (In terms of the Array API it's best to say "0d array", as the term "array scalars" is more a NumPy-specific. We also use the term "scalars" to refer to Python's builtins `bool`/`int`/`float`.)

Hmm, `test_full` has been working fine for a few libraries now. My guess is a problem in the underlying assertion in `ph.assert_fill()`:
```python
assert xp.all(xp.equal(out, xp.asarray(fill_value, dtype=dtype)))
```
Maybe your implementation of `xp.equal()` or `xp.all()` is problematic if they doesn't play nicely with 0-sided arrays, e.g. if `out=empty((0,))`. Here's how it plays out with NumPy right now, which I believe is the correct behaviour.
```python
>>> from numpy import array_api as xp
>>> out = xp.zeros((0,), dtype=xp.uint8)
>>> out.shape
(0,)
>>> fill = xp.asarray(0, dtype=xp.uint8))
>>> fill.shape
()
>>> xp.equal(out, fill)  # broadcasting rules would have fill turn into an empty array
empty((0,), dtype=bool)
>>> xp.all(xp.equal(out, fill))
Array(True, dtype=bool)
```

**Comment by rgommers** [comment]
This is a lot easier to understand if you look at the actual types and not just shapes:
```python
>>> x = np.array([])  # 1-D array
>>> x.shape
(0,)
>>> type(x)
<class 'numpy.ndarray'>
>>> y = np.array(1)  # 0-D array
>>> y.shape
()
>>> y.ndim
0
>>> s = np.int64(1)  # "array scalar", i.e. instance of a dtype type with array-like methods
>>> s.shape
()
>>> type(s)
<class 'numpy.int64'>
```
The name "array scalar" (as used in https://numpy.org/doc/stable/reference/arrays.scalars.html#scalars) is a bit unfortunate.

Now for _arrays_, we have "empty array" meaning `x.size == 0` and "0-D array" meaning `x.ndim == 0` (and size is `1`).

**Comment by djl11** [comment]
Thanks a lot for making these points, yes this is all super clear, and your speculation about the reason for failure is correct @honno. Will dig a little deeper and get my implementations of `xp.equal()` and `xp.all()` working properly. Thanks a lot both!

**Comment by leofang** [comment]
This is an important corner case and a nice discussion.
